// vue-example/src/infrastructure/components/ProductList.vue
<template>
  <ul>
    <li v-for="product in products " :key="product.id"> {{ product.title }}</li>
  </ul>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { getProducts } from '@/domain/repositories/product.repository'
import { Product } from '@/domain/models/Product'

export default defineComponent({
  name: 'ProductList',
  data () {
    return {
      products: [] as Product[]
    }
  },
  mounted () {
    getProducts().then(response => (this.products = response))
  }
})
</script>

// react-example/src/infrastructure/components/ProductList.tsx
import * as React from 'react'
import { Product } from '../../domain/models/Product'
import { getProducts } from '../../domain/repositories/product.repository'

export const ProductList: React.FC = () => {
  const [products, setProducts] = React.useState<Product[]>([])

  React.useEffect(() => {
    getProducts().then(setProducts)
  }, [])

  return (
    <ul>
      {products.map((product) => <li key={product.id}>{product.title}</li>)}
    </ul>
  )
}
