// vue-example/src/infrastructure/components/ProductList.vue
<template>
  <ul>
    <li v-for="product in products " :key="product.id">
      <button @click="() => { onSelectProduct(product) }">{{ product.title }}</button>
    </li>
  </ul>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import type { PropType } from 'vue'
import { Product } from '@/domain/models/Product'

export default defineComponent({
  name: 'ProductList',
  props: {
    products: { type: Array as PropType<Product[]> },
    onSelectProduct: { type: Function }
  }
})
</script>

// next-example/src/infrastructure/components/ProductList.tsx
import * as React from 'react'
import { Product } from '../../domain/models/Product'

type ProductListProps = {
  products: Product[]
  onSelectProduct: (product: Product) => void
}

export const ProductList: React.FC<ProductListProps> = ({ products, onSelectProduct }) =>
  (
    <ul>
      {products.map((product) => <li key={product.id}>
        <button onClick={() => {
          onSelectProduct(product)
        }}>{product.title}</button>
      </li>)}
    </ul>
  )
